export const SEED_DATA = [
    {
        title: 'SZÓLÁSOK ÉS KÖZMONDÁSOK',
        puzzles: [
            'KI KORÁN KEL ARANYAT LEL', 'NEM MINDEN ARANY AMI FÉNYLIK', 'AJÁNDÉK LÓNAK NE NÉZD A FOGÁT', 'SOK LÚD DISZNÓT GYŐZ', 'ADDIG NYÚJTÓZKODJ AMÍG A TAKARÓD ÉR',
            'AMILYEN A MOSDÓ OLYAN AZ TÖRÖLKÖZŐ', 'A LÓNAK NÉGY LÁBA VAN MÉGIS MEGBOTLIK', 'EGY FECSKE NEM CSINÁL NYÁRT', 'JOBB MA EGY VERÉB MINT HOLNAP EGY TÚZOK', 'NEM ESIK MESSZE A MAJMA A FÁJÁTÓL',
            'A HAZUGOT HAMARABB UTOLÉRIK MINT A SÁNTA KUTYÁT', 'AKI MÁSNAK VERMET ÁS MAGA ESIK BELE', 'KÖZÖS LÓNAK TÚRÓS A HÁTA', 'NAGY FÁBA VÁGTA A FEJSZÉJÉT', 'LASSÚ VÍZ PARTOT MOS',
            'NEM AKARÁSNAK NYALÁS A VÉGE', 'KI MINT VET ÚGY ARAT', 'OLCSÓ HÚSNAK HÍG A LEVE', 'SZEGET SZEGGEL', 'AHOL FÜST VAN OTT TŰZ IS VAN',
            'MADARAT TOLLÁRÓL EMBERT BARÁTJÁRÓL', 'NAGYOT FORDULT A VILÁG', 'KIBÚJT A SZEG A ZSÁKBÓL', 'NEM MA SÜLT GALAMB REPPEN A SZÁJÁBA', 'A TŰRÉS IS JÓZANSÁG',
            'MINDEN JÓ HA A VÉGE JÓ', 'EBBŐL NEM ESZIK MESZET', 'KÉTSZER AD AKI GYORSAN AD', 'ESŐ UTÁN KÖPÖNYEG', 'FALRA FESTETT ÖRDÖG',
            'ZSENIÁLIS ÖTLET', 'VAK TYÚK IS TALÁL SZEMET', 'NINCSEN RÓZSA TÖVIS NÉLKÜL', 'JÓ PAP HOLTIG TANUL', 'AMIT MA MEGTEHETSZ NE HALASZD HOLNAPRA',
            'A KOCKA EL VAN VETVE', 'CSALÁNBA NEM ÜT A MENNYKŐ', 'NEM FÉL A JÓ EMBER A TÖRVÉNYTŐL', 'ALVÓ MACSKA NEM FOG EGERET', 'MINDENKI A MAGA SZERENCSÉJÉNEK KOVÁCSA',
            'PÉNZ BESZÉL KUTYA UGAT', 'NEM A RUHA TESZI AZ EMBERT', 'SZEGÉNY EMBER VÍZZEL FŐZ', 'TÖBB SZEM TÖBBET LÁT', 'TÜRELEM RÓZSÁT TEREM',
            'FALRA HÁNYT BORSÓ', 'NAGY HARANGOT KÖTÖTT AZ ORRÁRA', 'ELNYELI A FÖLD', 'ÁTESETT A LÓ TÚLSÓ OLDALÁRA', 'KORÁN JÖTT VENDÉGNEK AJTÓ MÖGÖTT A HELYE',
            'NYUGATÁVAL DICSÉRD A NAPOT', 'KÉSŐ BÁNAT EBGONDOLAT', 'MINDEN CSODA HÁROM NAPIG TART', 'KI KIVÁNCSI HAMAR MEGVÉNÜL', 'NAGY DOLOGBAN SOKAN TÉVEDNEK',
            'KUTYÁBÓL NEM LESZ SZALONNA', 'NEM REJTÉLY A JÓ INDULAT', 'A MUNKA NEMESÍT', 'NEM FÚJ A SZÉL HA NEM ZÖRÖG A HARASZT', 'NEM LEHET KÉT ÚRNAK SZOLGÁLNI',
            'AHÁNY HÁZ ANNYI SZOKÁS', 'AZ IDŐ PÉNZ', 'A TUDÁS HATALOM', 'SAJÁT BŐRÉN TANUL AZ EMBER', 'NEM ESZIK OLYAN FORRÓN A KÁSÁT',
            'A CÉL SZENTESÍTI AZ ESZKÖZT', 'NEM MINDENKINEK KEREK A VILÁG', 'TEGTEHETSZ EGY JÓ SZESSZIÓT', 'AKI MER AZ NYER', 'JÓ UTÁN ROSSZ ROSSZ UTÁN JÓ',
            'MINDEN KÖVET MEGMOZDÍT', 'KÖTÉLNEK ÁLL', 'KÉT TŰZ KÖZÉ SZORULT', 'CSEBERBŐL VEDERBE', 'ZÖLD ÁGRA VERGŐDIK',
            'KIVÁGJA A REZET', 'NESZE SEMMI FOGD MEG JÓL', 'LÓVÁ TESZ VALAKIT', 'ÚJSEPPENSŐ SZERELEM', 'ITATJA AZ EGEREKET',
            'LÓGATJA AZ ORRÁT', 'FÁRADT MINT A KUTYA', 'ÚSZIK AZ ÁRRA', 'A JÉG HÁTÁN IS MEGÉL', 'KÖTI AZ EBET A KARÓHOZ',
            'NEM LÁTJA A FÁTÓL AZ ERDŐT', 'BORSÓT HÁNY A FALRA', 'MINDEN LÉBEN KANÁL', 'SÖTÉTBEN MINDEN MACSKA FEKETE', 'EGY ICKE SÖR NEM TÉL',
            'NYELI MINT KACSA A NOKEDLIT', 'BELETÖRT A BICSKÁJA', 'KILÓG A LÓLÁB', 'HÁTTAL NEM KEZDÜNK MONDATOT', 'KÉT BALKÉZEL VAN',
            'KIPAKOLJA A KÁRTYÁKAT', 'MEGELŐZI A KORÁT', 'ÚGY ÉLNEK MINT A KUTYA ÉS A MACSKA', 'ESZI A KEFÉT', 'LEVESZI A LÁBÁRÓL'
        ]
    },
    {
        title: 'MAGYAR VÁROSOK',
        puzzles: [
            'BUDAPEST', 'DEBRECEN', 'SZEGED', 'MISKOLC', 'PÉCS', 'GYŐR', 'NYÍREGYHÁZA', 'KECSKEMÉT', 'SZÉKESFEHÉRVÁR', 'SZOMBATHELY',
            'SZOLNOK', 'TATABÁNYA', 'KAPOSVÁR', 'VESZPRÉM', 'BÉKÉSCSABA', 'ZALAEGERSZEG', 'EGER', 'NAGYKANIZSA', 'DUNAUJVÁROS', 'HÓDMEZŐVÁSÁRHELY',
            'SOPRON', 'BAJA', 'SZENTENDRE', 'SIÓFOK', 'ESZTERGOM', 'PÁPA', 'VÁC', 'GÖDÖLLŐ', 'ÓZD', 'MOSONMAGYARÓVÁR',
            'GYÖNGYÖS', 'KISKUNFÉLEGYHÁZA', 'AJKA', 'SALGÓTARJÁN', 'SZEKSZÁRD', 'HAJDÚSZOBOSZLÓ', 'KARCAG', 'SZARVAS', 'KOMÁROM', 'MÁTÉSZALKA',
            'KESZTHELY', 'OROSHÁZA', 'JÁSZBERÉNY', 'MOHÁCS', 'SZENTES', 'KAPUVÁR', 'MEZŐKÖVESD', 'TIHANY', 'VISEGRÁD', 'HATVAN',
            'CEGLÉD', 'NAGYKŐRÖS', 'DUNAKESZI', 'BUDAÖRS', 'SZIGETSZENTMIKLÓS', 'SZENTENDRE', 'GÖD', 'VÁCRÁTÓT', 'POMÁZ', 'BIATORBÁGY',
            'VECSÉS', 'GYÁL', 'DUNAHARASZTI', 'FÓT', 'SZÁZHALOMBATTA', 'MONOR', 'GÖDÖLLŐ', 'SÜLYSÁP', 'ERCSÍ', 'BUDAKESZI',
            'PILISVÖRÖSVÁR', 'TÖRÖKBÁLINT', 'MAGLÓD', 'ISASZEG', 'ÚJFEHÉRTÓ', 'TISZAVASVÁRI', 'NAGYKÁLLÓ', 'TISZAFÜRED', 'MEZŐTÚR', 'TÚRKEVE',
            'TISZAKÉCSKE', 'LAJOSMIZSE', 'CSONGRÁD', 'KISTELEK', 'MAKO', 'SZENTES', 'SZEGVAR', 'KISTELEK', 'MÓRAHALOM', 'JÁNOSHALMA',
            'KALOCSA', 'KISKUNHALAS', 'KISKUNMAJSA', 'KUNSZENTMIKLÓS', 'SOLTVADKERT', 'TOMPA', 'BÁCSALMÁS', 'HAJÓS', 'IZSÁK', 'KEREPES'
        ]
    },
    {
        title: 'FILMES IDÉZETEK',
        puzzles: [
            'AZ ERŐ LEGYEN VELED', 'HASTA LA VISTA BABY', 'AZ ÉLET OLYAN MINT EGY DOBOZ BONBON', 'HOUSTON VAN EGY KIS PROBLÉMÁNK', 'ÉNEKLEM A JÓKEDVET',
            'ÉG VELED ÉS KÖSZ A HALAKAT', 'A NEVEM BOND JAME BOND', 'NINCSEN JOBB HELY AZ OTTHONNÁL', 'EGY GYŰRŰ MIND FELETT', 'KÉREM A KÖVETKEZŐ KORREKCIÓT',
            'MINDIG IS ÉLTÜNK VALAHOGY', 'MIÉRT ILYEN KOMOLY EDDIE', 'CSAK ÚSSZ ÉS EVEZZ', 'TE SEM VAGY TÖKÉLETES', 'AZT HISZEM EZ EGY SZÉP BARÁTSÁG KEZDETE',
            'A PÉNZ SOHA NEM ALSZIK', 'NEM ÉN VAGYOK A TE APÁD', 'EGY JÓ COCOA SEGÍT A BAJBAN', 'KÉSZEN ÁLLSZ A JÁTÉKRA', 'A TUDÁS HATALOM',
            'MINDENT A MAGA IDEJÉBEN', 'NEM ZÖRÖG A HARASZT HA NEM FÚJJA A SZÉL', 'NEM VAGYOK ÉN MATRÓZ', 'EZ A VÁROS TÚL KICSI KETTŐNKNEK', 'KAPJ EL HA TUDSZ',
            'A FÉLELEM A SÖTÉT OLDAL KAPUJA', 'HÁT ELKEZDŐDÖTT', 'NEM SÉRTÉSNEK SZÁNTAM', 'VAN VALAMI A LEVEGŐBEN', 'A HOLNAP EGY ÚJ NAP',
            'FUSS FORREST FUSS', 'ÉREZEM A SEBESSÉG KÉNYSZERÉT', 'A JÖVŐT MI ÍRJUK', 'NEM MINDENKI ELLENSÉG', 'A CSALÁD A LEGFONTOSABB',
            'LÁTOM ÖNT', 'AZ IGAZSÁG ODAÁT VAN', 'NEM MEHETSZ ÁT', 'KÖSD BE MAGAD PAPA', 'EZ VESZÉLYES JÁTÉK',
            'SOHA NE MONDD HOGY SOHA', 'A REMÉNY JÓ DOLOG', 'EGY KIS TÜRELEM JÓT TESZ', 'NEM FELEJTÜNK', 'EZ MARADJON KÖZÖTTÜNK',
            'MINDEN JÓL ALAKUL', 'A BOSSZÚ HIDEGEN TÁLALVA A LEGJOBB', 'NAGY HATALOM NAGY FELELŐSSÉGGE JÁR', 'ÜDVÖZÖLLEK A VALÓ VILÁGBAN', 'KÉSZÜLJ A LEGROSSZABBRA',
            'EGY KIS KAVIÁR JÓT JELENT', 'ITT NINCSENEK SZABÁLYOK', 'A JÁTÉKNAK VÉGE', 'ÉN VAGYOK A VILÁG KIRÁLYA', 'SOHA NE ENGEDD EL',
            'CSAK EGY MARADHAT', 'A VALÓSÁG CSAK ILLÚZIÓ', 'A TIÉD VAGYOK', 'NEM BÁNOM MEGNÉZNI', 'EZ EGY CSODÁLATOS ÚT',
            'A SÖTÉTSÉG NEM AZ ELLENSÉGED', 'A HANGOK A FEJEMBEN VANNAK', 'VÁLASSZ KI EGY ÚTAT', 'A GYŐZTES MINDENT VISZ', 'AZ IDŐ JÁR',
            'NEM A SZÁMOK SZÁMÍTANAK', 'EZ A TE ÉLETED', 'LÉGY AZ AKI VAGY', 'SOHA NE ADD FEL', 'A TŰZ VELEM JÖN',
            'NEM HISZEK A KÍSÉRTETEKBEN', 'EGY ÚJ NAP KÖSZÖNT RÁNK', 'A CSODÁK LÉTEZNEK', 'EZ EGY ÚJ KEZDET', 'A MÚLT MÁR KÉSZ',
            'A JÖVŐ MÉG REJTÉLY', 'A MAI NAP EGY AJÁNDÉK', 'KÉSZEN ÁLLSZ A KALANDRA', 'NEM SZÁMÍT AZ ESŐ', 'A TÁNC AZ ÉLETEM',
            'NEM KELL FÉLNI A SÖTÉTBEN', 'A REJTÉLY MEGOLDÓDOTT', 'A KULCS A TE KEZEDBEN VAN', 'NEM VAGY EGYEDÜL A BAJBAN', 'A FÉNY UTAT MUTAT',
            'EZ A MI IDŐNK', 'A ZENE MINDENT LEGYŐZ', 'A BARÁTSÁG EGY KINCS', 'NEM KELL MINDIG NYERNI', 'A MOSOLY SEGÍT',
            'A SZÍVEDRE HALLGASS', 'EZ EGY SIKERES AKCIÓ', 'A TITOK KIDERÜLT', 'NEM JÁTSZUNK TÖBBÉ', 'A VÉGSŐ ÖSSZECSAPÁS'
        ]
    },
    {
        title: 'IRODALMI IDÉZETEK',
        puzzles: [
            'LENNI VAGY NEM LENNI EZ ITT A KÉRDÉS', 'TALPRA MAGYAR HÍ A HAZA', 'NEMZETEK KÖZÖTT SINCSEN SENKI MÁS', 'MINDEN EGÉSZ ELTÖRÖTT', 'CSAK AZ HAL MEG AKIT ELFELEDNEK',
            'HA A FÖLD ISTEN KALAPJA', 'JÓ SZÓVAL OKTATSD JÁTSZANI', 'MINDENIK EMBERNEK LELKÉBEN DAL VAN', 'EGY SZÓ SE ESSÉK RÓLA KÖZTÜNK', 'AZ EMBER KÜZD ÉS BÍZVA BÍZHATIK',
            'DUNA MENTÉN NEVELŐDÖTT NÉP', 'SZÉP VAGY GYÖNYÖRŰ VAGY MAGYARORSZÁG', 'NEM LOPUNK MI CSAK KÉRÜNK', 'MINDEN KI JÓ ÉS MINDEN KI ROSSZ', 'FÖL FEL TI RABJAI A FÖLDNEK',
            'SZEGÉNY ANYÁM CSAK EGYET KERESETT', 'HULL A REKKENŐ SÁRGA NYÁR', 'A REJTÉLY NYITJA', 'NEM A TIÉD A JOG', 'SORSOM A SZABADSÁG',
            'MINDIG VAN VALAMI FÉNY', 'A SZÍVNEK VANNAK INDOKAI', 'SZERETNI VALAKIT AZT JELENTI', 'A LEGFONTOSABB DOLGOK LÁTHANKATLANOK', 'HA NEM JÖN SENKI VELED',
            'AZ ÉLET EGY JÁTSZÓTÉR', 'NEM AZÉRT VAGYUNK ITT HOGY FÉLJÜNK', 'A GONDOLAT SZABAD MINT A MADÁR', 'NEM SOKASÁG HANEM LÉLEK', 'CSAK A JÓK MENNEK EL',
            'AZ IDŐ MINDENT MEGOLD', 'AZ ÉN SZÍVEMBEN NINCS HARAG', 'MINDEN EMBER EGY KÜLÖN VILÁG', 'A SZÓ ELREPÜL AZ ÍRÁS MEGMARAD', 'NEM A SIKER A LÉNYEG',
            'A TUDÁS VILÁGOSSÁG', 'SZERESD A FELEBARÁTOD', 'NEM MINDEN NAP KARÁCSONY', 'AZ ÉLET EGY AJÁNDÉK', 'MINDEN KEZDET NEHÉZ',
            'A TISZTA LELKIISMERET ARANYAT ÉR', 'MINDENKINEK MEG VAN A MAGA KERESZTJE', 'NEM SZEGÉNY AZ AKI KEVESSEL BEÉRI', 'A REMÉNY HAL MEG UTOLJÁRA', 'AZ ÉLET HARC ÉS MUNKA',
            'MINDENKI A MAGA UTÁT JÁRJA', 'A JÓ BARÁT AZ ÉLET DÍSZE', 'NEM KELL MINDIG BÁNKÓDNI', 'A SZERETET MINDENT LEGYŐZ', 'NEM VAGYUNK EGYEDÜL',
            'GOLYÓK ZÁPOROZNAK', 'VÉGTLEN KÉKSÉG', 'SZÁRNYAL AZ ELME', 'A KÖLTŐ NEM HAZUDIK', 'A SZÉPSÉG MENTI MEG A VILÁGOT',
            'ÉG ÉS FÖLD KÖZÖTT', 'A SORS KEREKE FOROG', 'NINCS ÚJ A NAP ALATT', 'A TISZTA SZÍV TÖBBET ÉR', 'NEM AZ ÉVEK SZÁMÍTANAK',
            'A KÖNYV EGY TÜKÖR', 'A GONDOLATOKNAK SÚLYA VAN', 'NEM MINDEN TÖRTÉNET VÉGZŐDIK JÓL', 'A KÖLTÉSZET A LÉLEK ZENEJE', 'MINDEN EMBER EGY REJTÉLY',
            'A JÖVŐ A BÁTOROKÉ', 'A BÖLCSESSÉG HALK', 'A FÉLELEM ROSSZ TANÁCSADÓ', 'MINDEN PILANAT EGY KEZDET', 'A SORSOD A TE KEZEDBEN VAN',
            'NEM A RUHA TESZI', 'A IGAZ SZÓ UTAT TÖR', 'A BÉKE A LEGNAGYOBB KINCS', 'NEM MINDENKI VAK AKI LEHUNYJA A SZEMÉT', 'A TÜRELEM KESERŰ DE GYÜMÖLCSE ÉDES',
            'A HIT HEGYEKET MOZGAT', 'A JÓ CSELÉD KINCS', 'NEM MINDEN UTAD KÖNNYŰ', 'A TUDÁS NEM SÚLY', 'A SZERETET NEM ISMER HATÁROKAT',
            'A JÓ KÖNYV MEGVÁLTOZTAT', 'A GONDOLAT HATALMASABB A KARDNÁL', 'NEM KELL FÉLNI A VÁLTOZÁSTÓL', 'A LÉLEK SOHA NEM ÖREGSZIK', 'A CSEND IS EGY VÁLASZ',
            'MINDEN JÓ INDULAT MEGTÉRÜL', 'A IGAZSÁG SZABADÍT FEL', 'NEM MINDENKI ELLENSÉG AKI ANNAK LÁTSZIK', 'A JÓ BARÁTSÁG ÖRÖK', 'A REMÉNY EGY VITORLA'
        ]
    },
    {
        title: 'FILMEK',
        puzzles: [
            'A GYŰRŰK URA', 'VISSZA A JÖVŐBE', 'PULP FICTION', 'A REMÉNY RABJAI', 'GLADIÁTOR', 'STAR WARS', 'INCEPTION', 'AVATAR', 'TITANIC', 'A KERESZTAPA',
            'A SÖTÉT LOVAG', 'FORREST GUMP', 'MÁTRIX', 'JURASSIC PARK', 'GLADIATOR', 'SCHINDLER LISTÁJA', 'KULP FICTION', 'CSLILLAGOK KÖZÖTT', 'SINKING OUT LOUD', 'A JÓ A ROSSZ ÉS A CSÚF',
            'VOLT EGYSZER EGY VADNYUGAT', 'AMELIE CSODÁLATOS ÉLETE', 'SZTÁRBAN SZTÁR', 'A NYOLCADIK UTAS A HALÁL', 'RAGADOZÓ', 'TERMINATOR KETTŐ', 'VISSZATÉRŐ', 'A PIANISTA',
            'A LEVÉL', 'SZELEK SZÁRNYÁN', 'A KOCKA', 'A KIVÁLASZTOTT', 'SZEGÉNY LEGÉNYEK', 'KONTROLL', 'VALAMI AMERIKA', 'ÜVEGTIGRIS', 'A TANÚ', 'MACSKAFOGÓ',
            'INDUL A BAKTERHÁZ', 'HYPPOLIT A LAKÁJ', 'LIZA A RÓKATÜNDÉR', 'KINCSEM', 'A VISZKIS', 'SAUL FIA', 'TESTRŐL ÉS LÉLEKRŐL', 'A REJTÉLY', 'A KÓD',
            'AZ UTOLSÓ SZAMURÁJ', 'FARKASOKKAL TÁNCOLÓ', 'EGY CSODÁLATOS ELME', 'A MAJOMBOLYGÓ', 'A JÖVŐ HŐSE', 'IDŐVONAL', 'A SÖTÉTSÉG UTÁN', 'A KINCSTÁR',
            'A KIVÁLASZTOTTAK', 'AZ UTOLSÓ EMBER', 'A KOCKÁZAT', 'A GYŐZTES', 'A TIÉD VAGYOK SOHA', 'A MENEKÜLŐ', 'A SIKER ÚTJA', 'A KÓDNEVÜNK',
            'A REJTETT VÁROS', 'A VADON SZAVA', 'A FEKETE PÁRDUC', 'BOSZORKÁNYOK', 'A BÁTOR', 'A CSODACSAPAT', 'A JÉG KORSZAK', 'A JÁTSZMA',
            'A VADÁSZAT', 'A KÉM AKI SZERETETT ENGEM', 'A VILÁGOK HARCA', 'A FEKETE JEL', 'A TITKOK KAMRÁJA', 'A BÖLCSEK KÖVE', 'A TŰZ SERLEGE',
            'A FŐNIX RENDJE', 'A FÉLVÉR HERCEG', 'A HALÁL EREKLYÉI', 'A HOBBIT', 'A JÖVŐ KEZDETE', 'A HARC MEZŐ', 'A MENNYORSZÁG',
            'A SÖTÉT OLDAL', 'A VÉGSŐ JÁTÉK', 'A SORS KEREKE', 'A KÜLDETÉS', 'A REJTÉLYES SZIGET', 'A VADMACSKA', 'A KIS KIRÁLY',
            'A KÉM', 'A BÜSZKESÉG', 'A BUKÁS', 'A VITORLÁS', 'A TÚLÉLŐ', 'A VÁLASZUTAK', 'A CSODA', 'A TITKOS TÁRSASÁG'
        ]
    },
    {
        title: 'KÖNYVCÍMEK',
        puzzles: [
            'EGY MAGYAR NÁBOB', 'A PÁL UTCAI FIÚK', 'EGRI CSILLAGOK', 'ÁBEL A RENGETEGBEN', 'AZ EMBER TRAGÉDIÁJA', 'FALU JEGYZŐJE', 'KŐSZÍVŰ EMBER FIAI', 'ÁRVÁCSKA', 'ISKOLA A HATÁRON', 'SORSTALANSÁG',
            'ARANY EMBER', 'A KIS HERCEG', 'BŰN ÉS BŰNHŐDÉS', 'SZÁZ ÉV MAGÁNY', 'A DA VINCI KÓD', '1984 GEORGE ORWELL', 'ÁLLATFARM', 'A NYOMORULTAK', 'A JÁTSZMA', 'FAUST GOETHE',
            'ISTENI SZÍNJÁTÉK', 'A MESTER ÉS MARGARITA', 'ZABHEGYEZŐ', 'ÜVÖLTŐ SZELEK', 'BÜSZKESÉG ÉS BALÍTÉLET', 'ÚTON JACK KEROUAC', 'A NAGY GATSBY', 'DON QUIJOTE', 'MINDEN MEGVÁLTOZOTT', 'A KATEDRÁLIS',
            'A GYERTYÁK CSONKIG ÉGNEK', 'UTAZÁS A FÖLD KÖZÉPPONTJA FELÉ', 'A LÁTHATATLAN EMBER', 'NYOMORULTAK', 'A MAPPA', 'A SZENT PÉTER ESERNYŐJE', 'FARKASOK', 'UTAS ÉS HOLDVILÁG', 'A JANA', 'KÁLMAN ÉS KORREKCIÓ',
            'SZEGÉNY EMBEREK', 'A KIS HERCEGNŐ', 'A HÁROM TESTŐR', 'MONTE CRISTO GRÓFJA', 'A FEKETE VÁROS', 'A JÖVŐ SZÁZAD REGÉNYE', 'A KŐ BALZSAM', 'AZ UTOLSÓ MOHIKÁN', 'A KÉT LOTTI', 'ROBINSON CRUSOE',
            'A KÖNYV TOLVAJ', 'A SZÉL ÁRNYÉKA', 'A PARFÜM', 'SZERELMESEK', 'A TITKOS KERT', 'A KISASSZONY', 'A BÜSZKESÉG ÉS BALÍTÉLET', 'A SÖTÉT TORONY', 'A JÁTÉKOS', 'A SORS',
            'A KASTÉLY', 'A PER', 'A REJTÉLYES SZIGET', 'A JÖVŐ', 'A BOLDOGSÁG', 'A FEKETE OBELISZK', 'A DIADALÍV', 'A NYUGATI FRONTOS VÁLTOZÁS',
            'A HÁBORÚ ÉS BÉKE', 'ANNA KARENINA', 'A KÖZÉPPONT', 'A KÜLDETÉS', 'A BÁTOROK', 'A SÖTÉTSÉG', 'A FÉNY', 'A KULCS',
            'A TITOK', 'A JÁTSZÓTÉR', 'A KATEDRÁLIS', 'A SORS KEREKE', 'A TÚLÉLŐ', 'A KOCKÁZAT', 'A REJTETT ÚT', 'A FEKETE KÖNYV',
            'A KIS HERCEG', 'A KŐ', 'A SZÍV', 'A SZÉL', 'A TŰZ', 'A VÍZ', 'A LEVEGŐ', 'A FÖLD',
            'A TITKOS SZÁM', 'A KÓD', 'A MAPPA', 'A JEL', 'A VÁLASZ', 'A KÉRDÉS', 'A KÖNYV', 'A VÉG'
        ]
    },
    {
        title: 'HÍRES EMBEREK',
        puzzles: [
            'ALBERT EINSTEIN', 'MICHAEL JACKSON', 'ELVIS PRESLEY', 'WALT DISNEY', 'LEONARDO DA VINCI', 'ISAAC NEWTON', 'GALILEO GALILEI', 'CHARLES DARWIN', 'MARIE CURIE', 'SIGMUND FREUD',
            'PABLO PICASSO', 'VINCENT VAN GOGH', 'MIGUEL DE CERVANTES', 'WILLIAM SHAKESPEARE', 'WOLFGANG AMADEUS MOZART', 'LUDWIG VAN BEETHOVEN', 'JOHANN SEBASTIAN BACH', 'ABRAHAM LINCOLN', 'GEORGE WASHINGTON', 'WINSTON CHURCHILL',
            'MAHATMA GANDHI', 'NELSON MANDELA', 'MARTIN LUTHER KING', 'STEVEN SPIELBERG', 'TOM HANKS', 'BRAD PITT', 'ANGELINA JOLIE', 'JOHNNY DEPP', 'MADONNA', 'FREDDIE MERCURY',
            'MICK JAGGER', 'PAUL MCCARTNEY', 'JOHN LENNON', 'STEVE JOBS', 'BILL GATES', 'ELON MUSK', 'MARK ZUCKERBERG', 'CRISTIANO RONALDO', 'LIONEL MESSI', 'MICHAEL JORDAN',
            'MUHAMMAD ALI', 'ROGER FEDERER', 'NEIL ARMSTRONG', 'YURI GAGARIN', 'COCO CHANEL', 'BARACK OBAMA', 'QUEEN ELIZABETH', 'PRINCESS DIANA', 'MARILYN MONROE', 'CHARLIE CHAPLIN',
            'TOM CRUISE', 'ROBERT DE NIRO', 'AL PACINO', 'MORGAN FREEMAN', 'LEONARDO DICAPRIO', 'MERYL STREEP', 'JULIA ROBERTS', 'SANDRA BULLOCK', 'BILLIE EILISH', 'TAYLOR SWIFT',
            'BEYONCE', 'RIHANNA', 'EMINEM', 'JAY Z', 'DRAKE', 'JUSTIN BIEBER', 'SELENA GOMEZ', 'LADY GAGA', 'KATY PERRY', 'BRUNO MARS',
            'STEPHEN KING', 'JK ROWLING', 'GEORGE RR MARTIN', 'ERNEST HEMINGWAY', 'MARK TWAIN', 'AGATHA CHRISTIE', 'STEPHEN HAWKING', 'THOMAS EDISON', 'NIKOLA TESLA', 'ALEXANDER FLEMING',
            'SIGMUND FREUD', 'CARL JUNG', 'JEAN PAUL SARTRE', 'FRIEDRICH NIETZSCHE', 'IMMANUEL KANT', 'RENE DESCARTES', 'ARISZTOTELESZ', 'PLATÓN', 'SZOKRATÉSZ', 'JULIUS CAESAR',
            'NAGY SÁNDOR', 'KLEOPÁTRA', 'NAPÓLEON BONAPARTE', 'JEANNE DARC', 'KOLUMBUSZ KRISTÓF', 'VASCO DA GAMA', 'MARCO POLO', 'FERDINAND MAGELLAN', 'JAMES COOK', 'AMELIA EARHART'
        ]
    },
    {
        title: 'MAGYAR TÖRTÉNELMI SZEMÉLYEK',
        puzzles: [
            'SZENT ISTVÁN KIRÁLY', 'MÁTYÁS AZ IGAZSÁGOS', 'KOSSUTH LAJOS', 'SZÉCHENYI ISTVÁN', 'II RÁKÓCZI FERENC', 'SZENT LÁSZLÓ KIRÁLY', 'KÖNYVES KÁLMÁN', 'IV BÉLA A MÁSODIK ALAPÍTÓ', 'NAGY LAJOS KIRÁLY', 'LUXEMBURGI ZSIGMOND',
            'HUNYADI JÁNOS', 'KANIZSAI DOROTTYA', 'ZRÍNYI MIKLÓS', 'DOBÓ ISTVÁN', 'BATHORY ERZSÉBET', 'BETHLEN GÁBOR', 'PÁZMÁNY PÉTER', 'THÖKÖLY IMRE', 'MÁNYOKI ÁDÁM', 'DEÁK FERENC A HAZA BÖLCSE',
            'BATTHYÁNY LAJOS', 'PETŐFI SÁNDOR', 'GÖRGEY ARTÚR', 'BEM JÓZSEF BEM APÓ', 'ERZSÉBET KIRÁLYNÉ SISSI', 'TISZA ISTVÁN', 'KÁROLI MIHÁLY', 'HORTHY MIKLÓS', 'TELEKI PÁL', 'NAGY IMRE',
            'KÁDÁR JÁNOS', 'MINDSZENTY JÓZSEF', 'ANTALL JÓZSEF', 'GÖNCZ ÁRPÁD', 'ÁRPÁD VEZÉR', 'KOPPÁNY VEZÉR', 'GEJZA FEJEDELEM', 'SZENT IMRE HERCEG', 'ANONYMUS A JEGYZŐ', 'JULIANUS BARÁT',
            'KÁROLI GÁSPÁR', 'APÁCZAICSERE JÁNOS', 'BERCSÉNYI LÁSZLÓ', 'HADIK ANDRÁS', 'MARTINUVICS IGNÁC', 'WESSELÉNYI MIKLÓS', 'KÖLCSEY FERENC', 'VÖRÖSMARTY MIHÁLY', 'ARANY JÁNOS', 'ADY ENDRE',
            'JÓZSEF ATTILA', 'RADNÓTI MIKLÓS', 'MÓRICZ ZSIGMOND', 'KOSZTOLÁNYI DEZSŐ', 'BABITS MIHÁLY', 'JÓKAI MÓR', 'MIKSZÁTH KÁLMÁN', 'GARDONYI GÉZA', 'KRÚDY GYULA', 'KARINTHY FRIGYES',
            'LISZT FERENC', 'BARTÓK BÉLA', 'KODÁLY ZOLTÁN', 'ERKEL FERENC', 'MUNKÁCSY MIHÁLY', 'SREBL PÁL', 'CSONTVÁRY KOSZTKA TIVADAR', 'RIPPL RÓNAI JÓZSEF', 'YBL MIKLÓS', 'POLLACK MIHÁLY',
            'SEMMELWEIS IGNÁC', 'EÖTVÖS LORÁND', 'JEDLIK ÁNYOS', 'BOLYAI JÁNOS', 'PENTZ KÁLMÁN', 'SZILÁRD LEÓ', 'WIGNER JENŐ', 'TELLER EDE', 'NEUMANN JÁNOS', 'SZENT GYÖRGYI ALBERT',
            'KOCKA ERNŐ', 'PUSKÁS FERENC', 'PAPP LÁSZLÓ', 'HAJÓS ALFRÉD', 'BALCZÓ ANDRÁS', 'DARÁNYI KÁLMÁN', 'GÖMBÖS GYULA', 'BETHLEN ISTVÁN', 'PROHÁSZKA OTTOKÁR', 'BAJCSY ZSILINSZKY ENDRE'
        ]
    },
    {
        title: 'TÖRTÉNELMI ESEMÉNYEK',
        puzzles: [
            'A HONFOGLALÁS', 'AZ EGRI VÁR OSTROMA', 'MOHÁCSI VÉSZ', 'AZ AMERIKAI FELFEDEZÉSE', 'A FRANCIA FORRADALOM', 'A MUHI CSATA', 'A RIGÓMEZEI CSATA', 'NÁNDORFEHÉRVÁRI DIADAL', 'A REFORMÁCIÓ KEZDETE', 'A TRIDENTI ZSINAT',
            'A VESZTFÁLIAI BÉKE', 'A BÉCSI KONGRESSZUS', 'A WATERLOOI CSATA', 'AZ AMERIKAI FÜGGETLENSÉGI HÁBORÚ', 'AZ IPARI FORRADALOM', 'AZ ELSŐ VILÁGHÁBORÚ', 'A MÁSODIK VILÁGHÁBORÚ', 'A HIDEGHÁBORÚ', 'A BERLINI FAL LEBOMLÁSA', 'AZ EURÓPAI UNIÓ ALAPÍTÁSA',
            'AZ ARANYBULLA KIADÁSA', 'A VÉRERDŐ', 'A POZSONYI CSATA', 'A KENYÉRMEZEI CSATA', 'DÓZSA GYÖRGY FÉLE PARASZTHÁBORÚ', 'A REFORMKOR KEZDETE', 'A VILÁGOSI FEGYVERLETÉTEL', 'AZ ARADI VÉRTANÚK KIVÉGZÉSE', 'A MONARCHIA MEGALAKULÁSA', 'A TRIANONI BÉKESZERZŐDÉS',
            'A RENDSZERVÁLTOZÁS', 'A BUDAI VÁR BEVÉTELE', 'A KÖZÉPKOR KEZDETE', 'A MAJA CIVILIZÁCIÓ BUKÁSA', 'A RÓMAI BIRODALOM BUKÁSA', 'A KERESZTES HADJÁRATOK', 'A MAGNA CHARTA KIADÁSA', 'A SZÁZÉVES HÁBORÚ', 'A PESTISJÁRVÁNY EURÓPÁBAN', 'A BIZÁNCI BIRODALOM BUKÁSA',
            'A HARMINCÉVES HÁBORÚ', 'A NAPÓLEONI HÁBORÚK', 'A KRÍMI HÁBORÚ', 'A SAKK REVOLÚCIÓ', 'AZ UTOLSÓ ORSZÁGGYŰLÉS', 'AZ ÓKOR KEZDETE', 'TRÓJAI HÁBORÚ', 'A PERZSA HÁBORÚK', 'PELOPONNÉSZOSZI HÁBORÚ', 'NAGY SÁNDOR HADJÁRATAI',
            'PUN HÁBORÚK', 'SPARTACUS RABSZOLGAFELKELÉSE', 'RÓMA ALAPÍTÁSA', 'A Kereszténység elterjedése', 'A NÉPVÁNDORLÁS', 'A FRANK BIRODALOM MEGALAKULÁSA', 'VERDUNI SZERZŐDÉS', 'A SZENT RÓMAI BIRODALOM ALAPÍTÁSA', 'ANGLIA NORMAN HÓDÍTÁSA', 'AVIGNONI FÁSULÁS',
            'A NYUGATI EGYHÁZSZAKADÁS', 'A HUNDZSU DILASZTIA BUKÁSA', 'A SPANYOL INKVIZÍCIÓ KEZDETE', 'A MAGYAR KIRÁLYSÁG MEGALAPÍTÁSA', 'A TATÁRJÁRÁS', 'KRONSTADTI SZÖVETSÉG', 'A TIZENÖT ÉVES HÁBORÚ', 'A RÁKÓCZI SZABADSÁGHÁBORÚ', 'SZATMÁRI BÉKE', 'A PRAGMATICA SANCTIO KIADÁSA',
            'A HÉTÉVES HÁBORÚ', 'A RATSCHACHI CSATA', 'LENGYELORSZÁG FELOSZTÁSA', 'A LIPCEI CSATA', 'A NEMZETEK CSATÁJA', 'A GÖRÖG FÜGGETLENSÉGI HÁBORÚ', 'A KRÍMI HÁBORÚ VÉGE', 'AZ OLASZ EGYSÉG MEGALAKULÁSA', 'A NÉMET CSÁSZÁRSÁG KIKIÁLTÁSA', 'AZ OROSZ FORRADALOM',
            'A VERSAILLES I BÉKERENDSZER', 'A GAZDASÁGI VILÁGVÁLSÁG', 'A SPANYOL POLGÁRHÁBORÚ', 'A NÜRNBERGI PEREK', 'A NATO MEGALAKULÁSA', 'A VARSÓI SZERZŐDÉS MEGKÖTÉSE', 'A KÚBAI RAKÉTAVÁLSÁG', 'A VIETNÁMI HÁBORÚ', 'AZ AFGANISZTÁNI HÁBORÚ', 'A CSEREBOGÁR AKCIÓ'
        ]
    }
];